### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by williambj1** [khronokernel/Getting-Started-With-ACPI#1]
Hi @khronokernel !

I just read your guide briefly and discovered several issues.

  1. Fixing Embedded Controller (Laptop)

     According to the comments in ***`SSDT-EC`*** in OC's AcpiSamples

     > Try NOT to rename EC0, H_EC, etc. to EC. These devices are incompatible with macOS and may break at any time. AppleACPIEC kext must NOT load.

     and the following warning in OpenCore's manual,

     > Avoid renaming devices with ACPI patches. This may fail or perform improper renaming of unrelated devices (e.g. EC and EC0), be unnecessary, or even fail to rename devices in select tables.

     renaming is certainly not an ideal solution for EC issues, however, for Laptops, I understand that EC must not be set to off by the `_STA` method since batteries and other stuff are related to the original EC. Furthermore, my laptop (Asus 300 series motherboard) experiences a kernel panic after renaming EC. The solution I'm using now is faking a new EC while leaving the original `EC0` not disabled, but this causes AppleACPIEC to continue to load under boot-ec (see ioreg attachment). I'm wondering is there a better solution for this? Is it better to disable AppleACPIEC by other methods while leaving two EC with different `_HID` in macOS?

      [IOREG.zip](https://github.com/khronokernel/Getting-Started-With-ACPI/files/4191591/IOREG.zip)

  2. Fixing Backlight

     As the same reason given above, `PCI0.IGPU` will only occur in by abusing ACPI renaming since no hacks will have `IGPU` as the name for Intel GPUs natively, thus it is not recommended. BTW, Injecting `PNLF` under `_SB_` also works fine.

  3. Trackpad GPIO

     ***`SSDT-GPIO`*** doesn't make sense to me. According to my experience (I helped i2c trackpad issues for almost 100 laptops), the `_STA` method is present under `GPI0` in every laptop. Another injection of `_STA` via external SSDT will cause an **ACPI ERROR**. To verify this, simply paste the contents in your ***`SSDT-GPIO`*** into a laptop's DSDT and you'll see the error generated by iasl.

     - GPI0 Example in my DSDT

       ```swift
           Scope (_SB.PCI0)
           {
               Device (GPI0)
               {
                   Method (_HID, 0, NotSerialized)
                   {
                       If ((GPHD == One))
                       {
                           Return ("PNP0C02")
                       }

                       If ((PCHS == PCHH))
                       {
                           Return ("INT3450")
                       }

                       Return ("INT34BB")
                   }
                   ... /* Content excluded */
                   Method (_STA, 0, NotSerialized)
                   {
                       If ((GPHD == One))
                       {
                           Return (0x03)
                       }

                       Return (0x0F)
                   }
               }
            }
       ```

       In this example, GPIO can be easily enabled by setting a value that is not equal to `One` into `GPHD`

     - Some laptops contain a variable `GPEN` (I guess it stands for GPIO Enable) to control the return value of the `_STA` method, the solution example can be found in the OC-little project [link](https://github.com/daliansky/OC-little/blob/master/10-2-OCI2C-GPIO%E8%A1%A5%E4%B8%81/SSDT-OCGPI0-GPEN.dsl)

  4. Fixing I2C (XOSI)

     This patch doesn't make sense to me as well. `XOSI` is an extremely dirty hack that not only breaks the ACPI Specification but the entire multisystem support. This patch is very likely to cause a "blue screen" with an ACPI Error when booting Windows via OpenCore.

      > Note from OpenCore's manual
      >
      > Avoid patching _OSI to support a higher level of feature sets unless absolutely required. Commonly this enables a number of hacks on APTIO firmwares, which result in the need to add more patches. Modern firmwares generally do not need it at all, and those that do are fine with much smaller patches.

     By default, macOS will be treated as "Linux" for maximum compatibility in ACPI and several behaviors/devices will be disabled. Although this affects the I2C trackpad (causes returning only the slave address inside the `SBFB` method instead of the interrupt pins stored in `SBFI` & `SBFG`), it's better to tweak some variables in the `_STA` method (so far never experienced exceptions that causes failure) or using binary find & replace to disable the original device, then spoof a new trackpad device with a different name and a patched `_CRS` & `_STA` [example](https://github.com/daliansky/OC-little/tree/master/10-1-OCI2C-TPXX%E8%A1%A5%E4%B8%81%E6%96%B9%E6%B3%95)

     Some Hackintoshers created a tweaked ***`SSDT-XOSI`*** that contains an `If (_OSI ("Darwin"))` check and returns the original `_OSI` value when booting Windows. However, this somehow cheats the user himself and still violates the warning given by vit.

---

Besides those issues, I'd suggest you to introduce some usage examples of `If (_OSI ("Darwin"))` and `If (CondRefOf ())` if possible since I personally believe this is the core part of adjusting SSDTs.

---

Currently, we have a project in the Chinese Hackintosh Community called **[OC-little](https://github.com/daliansky/OC-little)**, most of the patches inside are written by an experienced hardware engineer & expert 宪武(Xian Wu). As one of the maintainers of the **[OC-little](https://github.com/daliansky/OC-little)** project, I sincerely welcome you to use the resources inside to write your guide and share it with English speakers worldwide.

Thank you for spending so much time and effort investigating ACPI and summarizing it into your vivid language, I really appreciate it.

> Edit1: Grammar and clarification
> Edit2: Grammar

**Comment by khronokernel** [comment]
@williambj1 Hello, thank you for the detailed issues. Really appreciate it!

**Issue 1:**
> The solution I'm using now is faking a new EC while leaving the original EC0 not disabled, but this causes AppleACPIEC to continue to load under boot-ec

The problem with this solution is I've actually found cases with laptops where creating a fake EC confuses the system greatly, specifically macOS will seem to prioritize the PC's original EC over the SSDT still causing a stall in the early PCI configuration stage. 

Back in July, I experimented with OpenCore's kext block feature which did in fact work quite well but as mentioned many times by Vit and Download-Fritz this is not a stable solution. kextd will usually just load the kext off of disk later.  I did also try making a plist-only kext but due to it being a plugin of another kext it failed.

Theoretically we could look into a kext patch of ACPIEC similar to what NoOne/IOIIIO originally did with [NullCPUPowerManagement](https://www.insanelymac.com/forum/topic/341340-superior-kext-patch-based-alternative-for-nullcpupm/) that was later adapted into OpenCore as DummyPowerManagement. I can ask NoOne/IOIIIO for some help on this matter

**Issue 2:**
Yeah this is just an issue on my part, will be corrected shortly. For some reason I thought there were some Lenovo's with `PCI0.IGPU` though I'm likely mixing up their EC naming instead. Though I did forget to add  `VID0` and `GPU0`as those pop up fro time to time

**Issue 3:**
> SSDT-GPIO doesn't make sense to me. According to my experience (I helped i2c trackpad issues for almost 100 laptops), the _STA method is present under GPI0 in every laptop. Another injection of _STA via external SSDT will cause an ACPI ERROR

This was based off of Fewtarius's work on his [Laptop guide](https://fewtarius.gitbook.io/laptopguide/), this does make sense why it doesn't work now that you've shown me so thank you. If it's alright I'd like to adapt the example SSDT you provided into the guide. I'll likely add the edge case where GPIO _STA doesn't exist though I'll need to ask for clarification from Fewtarius on this.

**Issue 4:**

Yeah XOSI is a very dirty hack, not proud of including it to begin with but I was a little limited on options at the time I wrote it. The idea of a fake trackpad just for macOS sounds like a much cleaner and safer solution

Again thank you much for the issues, happy I can clean it up a little and good luck with the [OC-Little](https://github.com/daliansky/OC-little) project, looks great!
